name: Deploy to Docker Hub

on:
  push:
    branches: [ master, main ]

jobs:
  push_to_docker_hub:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v3

      - name: 'Login to Docker Hub'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: 'Install npm dependencies'
        run: npm ci

      - name: 'Build JS files'
        run: npm run build

      - name: 'Build and push docker image'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: joaquinmaier/asr-devops-i:latest
